version: 2

updates:
  - package-ecosystem: nuget
    directory: /backend
    target-branch: develop
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      nuget-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /frontend
    target-branch: develop
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      npm-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      actions-minor-and-patch:
        update-types:
          - minor
          - patch
