// <auto-generated />
using System;
using GamesHud.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamesHud.Api.Persistence.Migrations
{
    [DbContext(typeof(GamesHudDbContext))]
    [Migration("20260826031321_AddProvisioningStateMachine")]
    partial class AddProvisioningStateMachine
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("GamesHud.Api.Persistence.Models.ManagedGameServerRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallationType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("LifecycleState")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("RuntimeType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("managed_game_servers", (string)null);
                });

            modelBuilder.Entity("GamesHud.Api.Persistence.Models.PersistenceMetadataRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("persistence_metadata", (string)null);
                });

            modelBuilder.Entity("GamesHud.Api.Persistence.Models.PortReservationRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Exposure")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("GameServerId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PortDefinitionId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProvisioningOperationId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProvisioningOperationId");

                    b.HasIndex("GameServerId", "PortDefinitionId")
                        .IsUnique();

                    b.HasIndex("Protocol", "Port")
                        .IsUnique();

                    b.ToTable("port_reservations", (string)null);
                });

            modelBuilder.Entity("GamesHud.Api.Persistence.Models.ProvisioningOperationRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActiveSlot")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStep")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessageSafe")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("GameServerId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("PipelineVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameServerId");

                    b.HasIndex("GameServerId", "Type", "ActiveSlot")
                        .IsUnique();

                    b.ToTable("provisioning_operations", (string)null);
                });

            modelBuilder.Entity("GamesHud.Api.Persistence.Models.ProvisioningStepRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempt")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CompensationCompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompensationStartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureType")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OperationId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("RetryClassification")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("SafeErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SideEffectClassification")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("StepId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OperationId", "Sequence")
                        .IsUnique();

                    b.HasIndex("OperationId", "StepId")
                        .IsUnique();

                    b.ToTable("provisioning_steps", (string)null);
                });

            modelBuilder.Entity("GamesHud.Api.Persistence.Models.StorageReservationRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameServerId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ownership")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProvisioningOperationId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageDefinitionId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProvisioningOperationId");

                    b.HasIndex("RelativePath")
                        .IsUnique();

                    b.HasIndex("GameServerId", "StorageDefinitionId")
                        .IsUnique();

                    b.ToTable("storage_reservations", (string)null);
                });

            modelBuilder.Entity("GamesHud.Api.Persistence.Models.PortReservationRecord", b =>
                {
                    b.HasOne("GamesHud.Api.Persistence.Models.ManagedGameServerRecord", "GameServer")
                        .WithMany("PortReservations")
                        .HasForeignKey("GameServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamesHud.Api.Persistence.Models.ProvisioningOperationRecord", "ProvisioningOperation")
                        .WithMany("PortReservations")
                        .HasForeignKey("ProvisioningOperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameServer");

                    b.Navigation("ProvisioningOperation");
                });

            modelBuilder.Entity("GamesHud.Api.Persistence.Models.ProvisioningOperationRecord", b =>
                {
                    b.HasOne("GamesHud.Api.Persistence.Models.ManagedGameServerRecord", "GameServer")
                        .WithMany("ProvisioningOperations")
                        .HasForeignKey("GameServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameServer");
                });

            modelBuilder.Entity("GamesHud.Api.Persistence.Models.ProvisioningStepRecord", b =>
                {
                    b.HasOne("GamesHud.Api.Persistence.Models.ProvisioningOperationRecord", "Operation")
                        .WithMany("Steps")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("GamesHud.Api.Persistence.Models.StorageReservationRecord", b =>
                {
                    b.HasOne("GamesHud.Api.Persistence.Models.ManagedGameServerRecord", "GameServer")
                        .WithMany("StorageReservations")
                        .HasForeignKey("GameServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamesHud.Api.Persistence.Models.ProvisioningOperationRecord", "ProvisioningOperation")
                        .WithMany("StorageReservations")
                        .HasForeignKey("ProvisioningOperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameServer");

                    b.Navigation("ProvisioningOperation");
                });

            modelBuilder.Entity("GamesHud.Api.Persistence.Models.ManagedGameServerRecord", b =>
                {
                    b.Navigation("PortReservations");

                    b.Navigation("ProvisioningOperations");

                    b.Navigation("StorageReservations");
                });

            modelBuilder.Entity("GamesHud.Api.Persistence.Models.ProvisioningOperationRecord", b =>
                {
                    b.Navigation("PortReservations");

                    b.Navigation("Steps");

                    b.Navigation("StorageReservations");
                });
#pragma warning restore 612, 618
        }
    }
}
