// <auto-generated />
using System;
using GamesHud.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamesHud.Api.Persistence.Migrations
{
    [DbContext(typeof(GamesHudDbContext))]
    [Migration("20260915122024_AddDurableRuntimeImageIdentity")]
    partial class AddDurableRuntimeImageIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("GamesHud.Api.Persistence.Models.ManagedGameConfigurationRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationKind")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("GameServerId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameServerId", "ConfigurationKind")
                        .IsUnique();

                    b.ToTable("managed_game_configurations", null, t =>
                        {
                            t.HasCheckConstraint("CK_managed_game_configurations_schema_version", "\"SchemaVersion\" > 0");
                        });
                });

            modelBuilder.Entity("GamesHud.Api.Persistence.Models.ManagedGameServerRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallationType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("LifecycleState")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("RuntimeType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("managed_game_servers", (string)null);
                });

            modelBuilder.Entity("GamesHud.Api.Persistence.Models.PersistenceMetadataRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("persistence_metadata", (string)null);
                });

            modelBuilder.Entity("GamesHud.Api.Persistence.Models.PortReservationRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Exposure")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("GameServerId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PortDefinitionId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProvisioningOperationId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProvisioningOperationId");

                    b.HasIndex("GameServerId", "PortDefinitionId")
                        .IsUnique();

                    b.HasIndex("Protocol", "Port")
                        .IsUnique();

                    b.ToTable("port_reservations", (string)null);
                });

            modelBuilder.Entity("GamesHud.Api.Persistence.Models.ProvisioningOperationRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActiveSlot")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStep")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessageSafe")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("GameServerId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("PipelineVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameServerId");

                    b.HasIndex("GameServerId", "Type", "ActiveSlot")
                        .IsUnique();

                    b.ToTable("provisioning_operations", (string)null);
                });

            modelBuilder.Entity("GamesHud.Api.Persistence.Models.ProvisioningReconciliationRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("AppliedCode")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempt")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OperationVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("PriorErrorCode")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("PriorFailureType")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("PriorStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("StepId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OperationId", "OperationVersion")
                        .IsUnique();

                    b.ToTable("provisioning_reconciliations", null, t =>
                        {
                            t.HasCheckConstraint("CK_reconciliation_outcome", "Outcome IN ('effect_exists', 'effect_absent', 'ambiguous')");
                        });
                });

            modelBuilder.Entity("GamesHud.Api.Persistence.Models.ProvisioningStepRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempt")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CompensationCompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompensationStartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureType")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OperationId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReconciledRetryAttempt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RetryClassification")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("SafeErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SideEffectClassification")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("StepId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OperationId", "Sequence")
                        .IsUnique();

                    b.HasIndex("OperationId", "StepId")
                        .IsUnique();

                    b.ToTable("provisioning_steps", (string)null);
                });

            modelBuilder.Entity("GamesHud.Api.Persistence.Models.RuntimeImageIntentRecord", b =>
                {
                    b.Property<string>("OperationId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovalSource")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedDigest")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("GameServerId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlatformArchitecture")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlatformOs")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlatformVariant")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Registry")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("TEXT");

                    b.Property<string>("Repository")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("RuntimeType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("VerificationState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("VerifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("VerifiedLocalImageId")
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("OperationId");

                    b.HasIndex("OperationId", "GameServerId");

                    b.HasIndex("GameServerId", "GameId", "RuntimeType");

                    b.ToTable("runtime_image_intents", null, t =>
                        {
                            t.HasCheckConstraint("CK_runtime_image_digest", "length(ApprovedDigest) = 71 AND substr(ApprovedDigest, 1, 7) = 'sha256:' AND substr(ApprovedDigest, 8) NOT GLOB '*[^0-9a-f]*'");

                            t.HasCheckConstraint("CK_runtime_image_id", "VerifiedLocalImageId IS NULL OR (length(VerifiedLocalImageId) = 71 AND substr(VerifiedLocalImageId, 1, 7) = 'sha256:' AND substr(VerifiedLocalImageId, 8) NOT GLOB '*[^0-9a-f]*')");

                            t.HasCheckConstraint("CK_runtime_image_platform", "PlatformOs IN ('linux', 'windows') AND PlatformArchitecture IN ('amd64', 'arm64')");

                            t.HasCheckConstraint("CK_runtime_image_state", "(VerificationState = 'pending' AND VerifiedLocalImageId IS NULL AND VerifiedAtUtc IS NULL) OR (VerificationState = 'verified' AND VerifiedLocalImageId IS NOT NULL AND VerifiedAtUtc IS NOT NULL)");

                            t.HasCheckConstraint("CK_runtime_image_version", "Version > 0");
                        });
                });

            modelBuilder.Entity("GamesHud.Api.Persistence.Models.StorageReservationRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameServerId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ownership")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProvisioningOperationId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageDefinitionId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProvisioningOperationId");

                    b.HasIndex("RelativePath")
                        .IsUnique();

                    b.HasIndex("GameServerId", "StorageDefinitionId")
                        .IsUnique();

                    b.ToTable("storage_reservations", (string)null);
                });

            modelBuilder.Entity("GamesHud.Api.Persistence.Models.ManagedGameConfigurationRecord", b =>
                {
                    b.HasOne("GamesHud.Api.Persistence.Models.ManagedGameServerRecord", "GameServer")
                        .WithMany("Configurations")
                        .HasForeignKey("GameServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameServer");
                });

            modelBuilder.Entity("GamesHud.Api.Persistence.Models.PortReservationRecord", b =>
                {
                    b.HasOne("GamesHud.Api.Persistence.Models.ManagedGameServerRecord", "GameServer")
                        .WithMany("PortReservations")
                        .HasForeignKey("GameServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamesHud.Api.Persistence.Models.ProvisioningOperationRecord", "ProvisioningOperation")
                        .WithMany("PortReservations")
                        .HasForeignKey("ProvisioningOperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameServer");

                    b.Navigation("ProvisioningOperation");
                });

            modelBuilder.Entity("GamesHud.Api.Persistence.Models.ProvisioningOperationRecord", b =>
                {
                    b.HasOne("GamesHud.Api.Persistence.Models.ManagedGameServerRecord", "GameServer")
                        .WithMany("ProvisioningOperations")
                        .HasForeignKey("GameServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameServer");
                });

            modelBuilder.Entity("GamesHud.Api.Persistence.Models.ProvisioningReconciliationRecord", b =>
                {
                    b.HasOne("GamesHud.Api.Persistence.Models.ProvisioningOperationRecord", null)
                        .WithMany()
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GamesHud.Api.Persistence.Models.ProvisioningStepRecord", b =>
                {
                    b.HasOne("GamesHud.Api.Persistence.Models.ProvisioningOperationRecord", "Operation")
                        .WithMany("Steps")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("GamesHud.Api.Persistence.Models.RuntimeImageIntentRecord", b =>
                {
                    b.HasOne("GamesHud.Api.Persistence.Models.ProvisioningOperationRecord", null)
                        .WithMany()
                        .HasForeignKey("OperationId", "GameServerId")
                        .HasPrincipalKey("Id", "GameServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamesHud.Api.Persistence.Models.ManagedGameServerRecord", null)
                        .WithMany()
                        .HasForeignKey("GameServerId", "GameId", "RuntimeType")
                        .HasPrincipalKey("Id", "GameId", "RuntimeType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GamesHud.Api.Persistence.Models.StorageReservationRecord", b =>
                {
                    b.HasOne("GamesHud.Api.Persistence.Models.ManagedGameServerRecord", "GameServer")
                        .WithMany("StorageReservations")
                        .HasForeignKey("GameServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamesHud.Api.Persistence.Models.ProvisioningOperationRecord", "ProvisioningOperation")
                        .WithMany("StorageReservations")
                        .HasForeignKey("ProvisioningOperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameServer");

                    b.Navigation("ProvisioningOperation");
                });

            modelBuilder.Entity("GamesHud.Api.Persistence.Models.ManagedGameServerRecord", b =>
                {
                    b.Navigation("Configurations");

                    b.Navigation("PortReservations");

                    b.Navigation("ProvisioningOperations");

                    b.Navigation("StorageReservations");
                });

            modelBuilder.Entity("GamesHud.Api.Persistence.Models.ProvisioningOperationRecord", b =>
                {
                    b.Navigation("PortReservations");

                    b.Navigation("Steps");

                    b.Navigation("StorageReservations");
                });
#pragma warning restore 612, 618
        }
    }
}
